name: "trigger-utils"

on:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: controlado/pengu-plugins
          event-type: updated-plugins